version: "3"

services:
  wordpress:
    depends_on:
      - db
    image: wordpress:5.7.2-fpm-alpine
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_TABLE_PREFIX: wp_
    volumes:
      - ./wordpress:/var/www/html
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - ./db:/var/lib/mysql
  nginx:
    depends_on:
      - wordpress

    image: nginx:alpine

    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./wordpress:/var/www/html

    ports:
      - 8080:80

volumes:
  wordpress:
  db:
  nginx:
