version: "3"

services:
  wordpress:
    depends_on:
      - db
    image: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_TABLE_PREFIX: wp_
    volumes:
      - ./wordpress:/var/www/html
    ports:
      - 8080:80

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - ./db:/var/lib/mysql
  # nginx:
  #   depends_on:
  #     - wordpress

  #   image: nginx:alpine

  #   volumes:
  #     - ./nginx:/etc/nginx/conf.d
  #     - ./wordpress:/var/www/html

  #   ports:
  #     - 8080:80

  nginx-minio:
    image: nginx:alpine
    volumes:
      - ./nginx-minio/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
    depends_on:
      - minio

  minio:
    image: minio/minio
    volumes:
      - ./data:/data
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  wordpress:
  db:
  # nginx:
  nginx-minio:
  minio:
